### ISSUE TITLE
WARNING: nut: command 'upsc' is not found 

### ISSUE THREAD

**Issue by pando85** [titpetric/netdata#25]
netdata log:
```bash
charts.d: WARNING: nut: command 'upsc' is not found in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
Dec  6 19:22:26 server docker/netdata_netdata_1[8562]: 2016-12-06 18:22:26: charts.d: ERROR: nut: module's 'nut' check() function reports failure.
```
I installed nut-client:
```bash
apt-get install nut-client
```

I don't know if this warning is important. I can make a PR if you want.

**Comment by titpetric** [comment]
Hello,

the docker image isn't meant to provide all the functionality of a non-isolated netdata container, but is very limited to the surface metrics which are common to all systems (cpu, disk, memory, network). Please see the "Additional notes" section of the main README.

I'm inclined to not install the upsc/nut-client software because it's not common to every system. You can work around it in two ways:

1. create your own docker image based on titpetric/netdata and install additional software,
2. install netdata along with additional software onto the host OS, without docker.

Based on what you submitted, I'm not even sure that you have UPS software that you would like to monitor with netdata, or if just the warning about missing software threw you off guard. If you're worried about the warning - it's not important. Netdata probes for available software on the system, trying to gauge as many metrics as possible. When some software doesn't exist, this results in a warning like the one above, and it can safely be ignored if needed.
