### ISSUE TITLE
Quick Question: Support passing custom config file for netdata

### ISSUE THREAD

**Issue by ammaskartik** [titpetric/netdata#44]
So I would like to enable 1 container as a registry to then have distributed monitoring for a private set of nodes. LMK if this is possible now, if not, I can make an update and submit a PR.

**Comment by titpetric** [comment]
Hello!

Recent commits have added streaming functionality via some additional ENV variables. Please check the README for some explanation on how to set it up.

PRs are welcome, but generally it's good to check in beforehand as some PRs get rejected due to usability concerns. I tend to keep the netdata image size as low as possible, and any addition that's implemented shouldn't depend on custom hardware (like sensors, UPS, etc.) which are not available in the majority of machines. In this case - it's a feature of netdata that could be included without additional penalties in regards to usability/size. :)

Best,
Tit
