### ISSUE TITLE
Add pushover

### ISSUE THREAD

**Issue by that1guy** [titpetric/netdata#52]
I'm not savvy enough to do this myself, but wanted to make a request to add pushover capability to docker container.  

Pushbullet iOS doesn't push notifications to the phone successfully anymore (known issue).

Love netdata!

**Comment by titpetric** [comment]
I think if you add a custom config into netdata, the recent PR enables you to do this.

Check the PR text of https://github.com/titpetric/netdata/pull/47

I didn't find a quick example for pushover config in the upstream repo, but you should figure that out for yourself. Closing this issue because it's not really related to the docker container, but if you want to submit a PR with specific env variable support, you're welcome to do so :)
